# Generated by Django 5.2.7 on 2025-11-20 05:23

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_course_alter_post_author_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover image for this post', null=True, upload_to=myapp.models.upload_to),
        ),
    ]
