# Generated by Django 5.2.7 on 2025-10-24 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
