# Generated by Django 5.2.7 on 2025-10-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssueList',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
